#!/usr/bin/env python
"""
Cleanup script for Alpha-FX project.
Removes all generated data and model files to allow a fresh start.
"""
import os
import shutil

# Directories to clean
DIRS_TO_CLEAN = [
    "data",
    "models",
]

# Files to clean (if specific files instead of dirs)
FILES_TO_CLEAN = [
    "best_params.txt",  # Generated by tune_agent.py
]

def clean():
    print("Alpha-FX Cleanup Script")
    print("=" * 40)
    
    for dir_path in DIRS_TO_CLEAN:
        if os.path.exists(dir_path):
            print(f"Removing directory: {dir_path}/")
            shutil.rmtree(dir_path)
        else:
            print(f"Directory not found (skipping): {dir_path}/")
    
    for file_path in FILES_TO_CLEAN:
        if os.path.exists(file_path):
            print(f"Removing file: {file_path}")
            os.remove(file_path)
        else:
            print(f"File not found (skipping): {file_path}")
    
    print("=" * 40)
    print("Cleanup complete. You can now run from scratch:")
    print("  1. python planning/run_pipeline.py")
    print("  2. python train_agent.py")
    print("  3. python backtest_agent.py")

if __name__ == "__main__":
    clean()
